
import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import { AuthProvider } from "@/components/session-provider/SessionProvider";

export const metadata = {
  title: "E-votar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className='min-h-screen flex flex-col'>
          <Navbar />
          <div className='flex-grow'>
            {children}
          </div>
          <Footer />
        </body>
      </AuthProvider>
    </html>
  );
}
